version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

executors:
  docker-executor:
    docker:
      - image: cimg/ruby:3.2.3-node

jobs:
  build:
    executor: docker-executor
    working_directory: ~/todo_list
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: build-docker-image
          command: docker
